### ISSUE TITLE
KeyError: 'joint_bone' of running eval\eval_frei.py

### ISSUE THREAD

**Issue by fighting5464** [ShaoXiang23/CLIP_Hand_Demo#2]
Hello,Mr.Guo:
    After study your Demo,I'm having some problems.The pre-training weight I used is 'CLIP_Hand_3D_PE_1104_3.pth.tar. ',than run main.py will yield results, but running eval/eval_frei.py will always yield an error. The error message is as follows:
/*
EvalTraceback (most recent call last):
  File "D:\Yiming\Desktop\CLIP_Hand_Demo-main666\CLIP_Hand_Demo-main6\eval\eval_frei.py", line 156, in <module>
    evaluation(
  File "D:\Yiming\Desktop\CLIP_Hand_Demo-main666\CLIP_Hand_Demo-main6\eval\eval_frei.py", line 148, in evaluation
    best_acc = validate(val_loader, model)
  File "D:\Yiming\Desktop\CLIP_Hand_Demo-main666\CLIP_Hand_Demo-main6\eval\eval_frei.py", line 49, in validate
    joint_bone = zipper['joint_bone'].to(device)
KeyError: 'joint_bone'
*/
    Can you give some suggestions?Looking forward to your reply.
    Thanks.

**Comment by ShaoXiang23** [comment]
Hi YiMing.

Sorry, I just saw your message.
I think the reason for this is because my Dataloader is a bit incomplete, I will fix this bug as soon as possible, and I will update the validation dataloader with the fixes within a week.

Thanks again for your support to my work.

Shaoxiang

**Comment by fighting5464** [comment]
Hi Mr.Guo，
    Thank you for your reply.

YiMing
